# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    app.broadcast_repository.orm:
        class: WhereCanIWatch\Infrastructure\Doctrine\ORMBroadcastRepository
        arguments:
            - "@doctrine.orm.entity_manager"

    app.broadcast_repository:
        alias: app.broadcast_repository.orm